[package]
name = "openapi-merge-cli"
description = "OpenAPI Merge Command Line Tool"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
openapi-merge.workspace = true
serde.workspace = true
